Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/05/2023
Var
// Seção de Declarações das variáveis
n : vetor[1..50] de real
i, num : inteiro
soma,  num2 : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
soma <- 1
para i de 1 ate 50 faca
num2 <- 1 / (i*2)
soma <- soma + num2
fimpara

escreva("A soma dos elementos é",soma)

Fimalgoritmo
